# Overwrite enter to go to directory instead of opening
[[mgr.prepend_keymap]]
on = "e"
run = """ shell --confirm 'wezterm start $EDITOR "$@"' """
desc = "Edit file in new window"

[[mgr.prepend_keymap]]
on = "o"
run = "open"
desc = "Open file in place"

# Toggle preview with the plugin
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Hide or show preview"
