[flavor]
# dark = "dracula"

[icon]
append_exts = [
	{ name = "norg", text = "󱞁", fg_dark = "#00afff", fg_light = "#0075aa" },
]
append_files = [
	{ name = "Justfile", text = "", fg_dark = "#00afff", fg_light = "#0075aa" },
]
prepend_dirs = [
	{ name = "Kuvat", text = "" },
	{ name = "muistiinpanot", text = "󱞁" },
	{ name = "repo", text = "" },
	{ name = "OmatProjektit", text = "" },
	{ name = "hdd", text = "" },
	{ name = "hauta", text = "" },
	{ name = "bin", text = "" },
]

# [filetype]
# append_rules = [
	# { mime = "inode/x-empty", fg = "#ff0000"},
	# { mime = "text/{plain,csv}", fg = "#00ff00"},
# ]
